const execa = require('execa');
const path = require('path');

async function prepare(pluginConfig, context) {
  const basePath = pluginConfig.pkgRoot ? path.resolve(context.cwd, pkgRoot) : context.cwd;
  console.log("preparing in version-plugin")
  const versionString = "// THIS FILE IS AUTOMATICALLY GENERATED\n#define WATERBEAR_FIRMWARE_VERSION " + context.nextRelease.version
  console.log( versionString )
  await execa.command(`echo '${versionString}' > src/version.h`, { cwd: basePath })
  console.log( "done" )
}

module.exports = { prepare };
