const execa = require('execa');

async function prepare(pluginConfig, context) {
  console.log("preparing in version-plugin")
  const versionString = "// THIS FILE IS AUTOMATICALLY GENERATED\n#define WATERBEAR_FIRMWARE_VERSION " + context.nextRelease.version
  console.log( versionString )
  await execa.command(`echo '${versionString}' > src/version.h`)
  console.log( "done" )
}

module.exports = { prepare };
